spring:
  datasource:
    url: jdbc:mysql://8.148.69.44:2306/zo_community?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Admin123qwertyuiop
    druid:
     max-active: 5
  redis:
    host: 47.111.123.211
    port: 6381
    password: lmx3IF3MeICgh8dCc5HR
  data:
    mongodb:
      uri: mongodb://comm:Admin123qwertyuiop@8.148.64.116:17017/community