server:
  port: ${sp.communityinfo}
spring:
  application:
    name: ${sn.communityinfo}
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${rocket-mq.name-server}
        bindings:
          output:
            producer:
              group: communityGroup
              sync: true
      bindings:
        output:
          destination: community-topic
          content-type: application/json
        input:
          destination: community-topic
          content-type: application/json
#开启MQ的日志
logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG